s=input("enter your number")
w=input("enter your number")
e=input("enter your number")
r=input("enter your number")
y=input("enter your number")
u=input("enter your number")
i=input("enter your number")
o=input("enter your number")
st={s,w,e,r,y,u,i,o}
print(st)
